import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1>
            welcome to quizland
          </h1>
        </div>

        <div className={styles.grid}>
          <a
            href="http://localhost:3000/user/login"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              login <span>-&gt;</span>
            </h2>
            <p>
              アカウントお持ちの方はこちら
            </p>
          </a>

          <a
            href="http://localhost:3000/user/register"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              register <span>-&gt;</span>
            </h2>
            <p>
              初めての方はこちら
            </p>
          </a>

          
          
        </div>
      </main>
    </>
  );
}
